apiVersion: apps/v1
kind: Deployment
metadata:
 name: config-deployment
spec:
 replicas: 2
 selector:
  matchLabels:
    app: nginx
 template:
   metadata:
      name: nginx-app
      labels:
        app: nginx
   spec:
     containers:
       - name: nginx-app
         image: nginx
         env:
          - name: myenv
            valueFrom:
              configMapKeyRef:
                 name: mymap
                 key: sample.conf
