apiVersion: apps/v1
kind: Deployment
metadata:
 name: secret-deployment
spec:
 replicas: 2
 selector:
  matchLabels:
    app: nginx
 template:
   metadata:
      name: nginx-app
      labels:
        app: nginx
   spec:
     containers:
       - name: nginx-app
         image: nginx
         volumeMounts:
           - name: secretdata
             mountPath: /tmp/secret
     volumes:
      - name: secretdata
        secret:
          secretName: mysecret
