apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    imagePullPolicy: Always
    name: ubuntu
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  ###########################################SecurityContexts######################################################################
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
  ##################################################################################################################################
    volumeMounts:    
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-696rq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: controlplane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  
  
