apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: application-probe
  name: application-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-probe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: readiness-probe
    spec:
      containers:
      - image: nginx
        name: nginx               
		    startupProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 20

