apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
 replicas: 2
 selector:
   matchLabels:
    app: nginx-app
 template:
   metadata:
     name: nginx-app
     labels:
       app: nginx-app
   spec:
     containers:
       - name: nginx-app
         image: nginx
         startupProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 20
